In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a2 = np.arange(start=0, stop=11, step=2)
print(a2)
a2 = a2.reshape(2, 3)
print(a2)
a2 = a2.reshape(3,2)
print(a2)
a2 = a2.flatten()
print(a2)

[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[ 0  2  4  6  8 10]


In [4]:
a3 = np.linspace(1.0, 5.0, num=5, retstep=True)
print(a3)

(array([1., 2., 3., 4., 5.]), 1.0)


In [5]:
a4 = [1,3,4]
for i in enumerate(a4):
    print(i)

(0, 1)
(1, 3)
(2, 4)


In [6]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [1]:
import numpy as np
array1 = np.random.randint(10, size=(3, 3)) 
array2 = np.random.randint(10, size=(3, 3)) 
print(array1) 
print(array2) 
res = np.dot(array1, array2)
print(res)

[[7 5 9]
 [7 6 6]
 [4 1 4]]
[[9 9 7]
 [2 0 8]
 [4 5 9]]
[[109 108 170]
 [ 99  93 151]
 [ 54  56  72]]


In [8]:
from scipy import stats as st
from numpy.linalg import inv
import scipy
import scipy.linalg
import numpy as np

In [9]:
matrix = np.random.randint(0,10,size=(3,3))
print(matrix)
matrixinv = inv(matrix)
print(matrixinv)
check = np.dot(matrix,matrixinv)
print(check)

[[6 6 5]
 [0 1 0]
 [9 4 0]]
[[-1.48029737e-17 -4.44444444e-01  1.11111111e-01]
 [ 3.33066907e-17  1.00000000e+00  0.00000000e+00]
 [ 2.00000000e-01 -6.66666667e-01 -1.33333333e-01]]
[[ 1.00000000e+00 -4.44089210e-16  0.00000000e+00]
 [ 3.33066907e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.44089210e-16  1.00000000e+00]]


In [10]:
z = np.random.randint(0,10,size=(3,3))
print(z)
P,L,U = scipy.linalg.lu(z)
print(P)
print(L)
print(U)

[[3 0 2]
 [6 5 4]
 [6 4 1]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  0.4 1. ]]
[[ 6.   5.   4. ]
 [ 0.  -2.5  0. ]
 [ 0.   0.  -3. ]]
