In [ ]:
pip install numpy

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(type(a))

In [ ]:
a2 = np.arange(start=0, stop=11, step=2)
print(a2)
a2 = a2.reshape(2, 3)
print(a2)
a2 = a2.reshape(3,2)
print(a2)
a2 = a2.flatten()
print(a2)

In [ ]:
a3 = np.linspace(1.0, 5.0, num=5, retstep=True)
print(a3)

In [ ]:
a4 = [1,3,4]
for i in enumerate(a4):
    print(i)

In [ ]:
a = np.zeros((3,4))
print(a)

In [3]:
import numpy as np
array1 = np.random.randint(10, size=(3, 3)) 
array2 = np.random.randint(10, size=(3, 3)) 
print(array1) 
print(array2) 
res = np.dot(array1, array2)

[[6 1 3]
 [4 3 1]
 [0 5 8]]
[[6 8 9]
 [1 0 3]
 [1 3 4]]


In [3]:
from scipy import stats as st
from numpy.linalg import inv
import scipy
import scipy.linalg
import numpy as np

In [4]:
matrix = np.random.randint(0,10,size=(3,3))
print(matrix)
matrixinv = inv(matrix)
print(matrixinv)
check = np.dot(matrix,matrixinv)
print(check)

[[8 9 5]
 [7 4 2]
 [8 4 2]]
[[ 2.22044605e-16 -1.00000000e+00  1.00000000e+00]
 [-1.00000000e+00  1.20000000e+01 -9.50000000e+00]
 [ 2.00000000e+00 -2.00000000e+01  1.55000000e+01]]
[[ 1.00000000e+00  0.00000000e+00  5.32907052e-15]
 [-8.88178420e-16  1.00000000e+00  0.00000000e+00]
 [-8.88178420e-16  0.00000000e+00  1.00000000e+00]]


In [5]:
z = np.random.randint(0,10,size=(3,3))
print(z)
P,L,U = scipy.linalg.lu(z)
print(P)
print(L)
print(U)

[[7 2 0]
 [2 8 8]
 [9 4 2]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[ 1.          0.          0.        ]
 [ 0.22222222  1.          0.        ]
 [ 0.77777778 -0.15625     1.        ]]
[[ 9.          4.          2.        ]
 [ 0.          7.11111111  7.55555556]
 [ 0.          0.         -0.375     ]]
